# Generated by Django 4.2.7 on 2023-11-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='revenue',
        ),
        migrations.AddField(
            model_name='company',
            name='carbon_neutral_efforts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='climate_change_considered_in_business',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='climate_related_financial_disclosure',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='disability_employment_efforts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='diversity_respecting_hr_policy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='dx_in_sustainability_context',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='engagement_survey_conducted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='esg_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='governance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='governance_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='grade_a_or_above',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='greenhouse_gas_reduction_efforts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='indicators_and_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='indicators_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='internal_systems_respecting_human_rights',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='market_product_classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='materiality_established',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='proactive_hiring_of_female_managers',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='risk_management',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='risk_management_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_data_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_large',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_medium',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_small',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='scope_3_inclusion_in_analysis',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stock_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='strategy_for_value_enhancement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='strategy_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='supply_chain_transparency_and_efficiency',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sustainability_approach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sustainability_committee_established',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='talent_development_indicators_and_performance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='talent_development_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='talent_indicators_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='talent_strategy_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='total_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
