# Generated by Django 4.2.7 on 2023-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_name_company_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='esg_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sales_amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
