# Generated by Django 4.2.7 on 2023-11-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_company_esg_score_alter_company_sales_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_classification', models.CharField(blank=True, max_length=10, null=True)),
                ('minor_classification', models.CharField(blank=True, max_length=10, null=True)),
                ('company_number', models.IntegerField(blank=True, null=True)),
                ('total_word_count', models.IntegerField(blank=True, null=True)),
                ('governance_word_count', models.IntegerField(blank=True, null=True)),
                ('strategy_word_count', models.IntegerField(blank=True, null=True)),
                ('talent_strategy_word_count', models.IntegerField(blank=True, null=True)),
                ('risk_management_word_count', models.IntegerField(blank=True, null=True)),
                ('indicators_word_count', models.IntegerField(blank=True, null=True)),
                ('talent_indicators_word_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
