# Generated by Django 4.2.7 on 2023-11-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_characternum_governance_word_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_classification', models.CharField(blank=True, max_length=10, null=True)),
                ('minor_classification', models.CharField(blank=True, max_length=10, null=True)),
                ('company_number', models.CharField(blank=True, max_length=10, null=True)),
                ('filling_company', models.CharField(blank=True, max_length=10, null=True)),
                ('filling_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('strategy_for_value_enhancement', models.CharField(blank=True, max_length=10, null=True)),
                ('dx_in_sustainability_context', models.CharField(blank=True, max_length=10, null=True)),
                ('sustainability_committee_established', models.CharField(blank=True, max_length=10, null=True)),
                ('materiality_established', models.CharField(blank=True, max_length=10, null=True)),
                ('supply_chain_transparency_and_efficiency', models.CharField(blank=True, max_length=10, null=True)),
                ('climate_change_considered_in_business', models.CharField(blank=True, max_length=10, null=True)),
                ('climate_related_financial_disclosure', models.CharField(blank=True, max_length=10, null=True)),
                ('greenhouse_gas_reduction_efforts', models.CharField(blank=True, max_length=10, null=True)),
                ('carbon_neutral_efforts', models.CharField(blank=True, max_length=10, null=True)),
                ('scope_3_inclusion_in_analysis', models.CharField(blank=True, max_length=10, null=True)),
                ('disability_employment_efforts', models.CharField(blank=True, max_length=10, null=True)),
                ('engagement_survey_conducted', models.CharField(blank=True, max_length=10, null=True)),
                ('internal_systems_respecting_human_rights', models.CharField(blank=True, max_length=10, null=True)),
                ('diversity_respecting_hr_policy', models.CharField(blank=True, max_length=10, null=True)),
                ('proactive_hiring_of_female_managers', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
