# Generated by Django 4.2.7 on 2023-12-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_wordrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=15, null=True)),
                ('heading', models.CharField(blank=True, max_length=15, null=True)),
                ('category1', models.CharField(blank=True, max_length=20, null=True)),
                ('category2', models.CharField(blank=True, max_length=20, null=True)),
                ('category3', models.CharField(blank=True, max_length=20, null=True)),
                ('category4', models.CharField(blank=True, max_length=20, null=True)),
                ('category5', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
