# Generated by Django 4.2.7 on 2023-12-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_inputcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='governance',
        ),
        migrations.RemoveField(
            model_name='company',
            name='indicators_and_goals',
        ),
        migrations.RemoveField(
            model_name='company',
            name='risk_management',
        ),
        migrations.RemoveField(
            model_name='company',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sustainability_approach',
        ),
        migrations.RemoveField(
            model_name='company',
            name='talent_development_indicators_and_performance',
        ),
        migrations.RemoveField(
            model_name='company',
            name='talent_development_policy',
        ),
        migrations.AddField(
            model_name='inputcategory',
            name='default_sentence',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
