# Generated by Django 4.2.7 on 2023-12-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_remove_company_governance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sustainability_approach',
            field=models.TextField(blank=True, null=True),
        ),
    ]
