# Generated by Django 5.0 on 2023-12-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_company_sustainability_approach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='esg_score',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sales_amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='stock_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
