# Generated by Django 5.0 on 2023-12-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_alter_company_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characternum',
            name='governance_word_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='characternum',
            name='indicators_word_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='characternum',
            name='major_classification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='characternum',
            name='minor_classification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='characternum',
            name='risk_management_word_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='characternum',
            name='strategy_word_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='characternum',
            name='talent_indicators_word_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='characternum',
            name='talent_strategy_word_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='characternum',
            name='total_word_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
